services:
  - type: web
    name: disney-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python glue_db.py"
    startCommand: "streamlit run dashbo.py"
    branch: main
